In [19]:
# from fastai.data.load import *
# from fastcore.foundation import *
# from fastcore.test import *
from fastai.text.all import *
from fastai.tabular.all import *
from fastai.data.external import *
from torch import tensor, stack
from PIL import Image

import pandas as pd

from torch.utils.data import DataLoader


In [ ]:
df = pd.DataFrame(
    { 'first' : [0, 0, 1, 1],
      'second' : [0, 1, 0, 1],
      'and' : [0, 0, 0, 1]}
)

splits = RandomSplitter(valid_pct=0.5)(range_of(df))

to = TabularPandas(df, procs = [Categorify],
                   cat_names = ['first', 'second'],
                   y_names='and',
                   splits=splits)

In [49]:
# dataset = torch.tensor((((0,0), 0), ((0,1), 0), ((1,0), 0), ((1,1), 0))
X = torch.tensor((0, 0, 0, 1, 1, 0, 1, 1), dtype= torch.float32).reshape(4, 2)
Y = torch.tensor((0, 0, 0, 1), dtype= torch.float32).reshape(4, 1)
# Y = (0, 0, 0, 1)
F_train = list(zip(X, Y))

for x, y in F_train:
    print(x, y)
    
x, y = F_train[0]
x. shape, y

tensor([0., 0.]) tensor([0.])
tensor([0., 1.]) tensor([0.])
tensor([1., 0.]) tensor([0.])
tensor([1., 1.]) tensor([1.])


(torch.Size([2]), tensor([0.]))

In [50]:
dl = DataLoader(F_train, batch_size=2)
dls = DataLoaders(dl, dl)
G = nn.Sequential(nn.Linear(2, 1), nn.Sigmoid())
learn = Learner(dls, G, opt_func=SGD, loss_func=nn.MSELoss)

In [51]:
learn.fit_one_cycle(1)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [ ]:
learn.show_results()